version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-tracker-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - expense-tracker

  db:
    image: mysql:8.0
    container_name: expense-tracker-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-expense_tracker}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - expense-db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - expense-tracker

  nginx:
    image: nginx:alpine
    container_name: expense-tracker-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - expense-tracker

networks:
  expense-tracker:
    driver: bridge

volumes:
  expense-db:
